#include <stdint.h>
const char mp_frozen_str_names[] = {
"magibit.py\0"
"\0"};
const uint32_t mp_frozen_str_sizes[] = {
2113,
};
const char mp_frozen_str_content[] = {
"from microbit import pin8, pin12, pin14, pin15\nfrom time import ticks_us\ndef motor_run(m, speed, direction):\n    if m != 1 and m != 2:\n        raise ValueError('Motor pin could only be 1 or 2')\n    if not (isinstance(speed, (int, float)) and (0 <= speed <= 1023)):\n        raise ValueError('Motor speed should be set between 0-1023')\n    if direction != 0 and direction != 1:\n        raise ValueError('Direction could only be 0 or 1')\n\n    if m == 1:\n        pin8.write_digital(direction)\n        pin12.write_analog(speed)\n    elif m == 2:\n        pin14.write_digital(direction)\n        pin15.write_analog(speed)\n\ndef motor_stop(m):\n    if m != 1 and m != 2:\n        raise ValueError('Motor pin could only be 1 or 2, if None then both m1, m2 will be off')\n        \n    if m == 1:\n        pin12.write_analog(0)\n    elif m == 2:\n        pin15.write_analog(0)\n    \ndef servo_angle(pin, angle, min_v=28.16, max_v=122.88):\n    if not 0 <= angle <= 180:\n        raise ValueError('Angle should be in range [0, 180]')\n    angle = int((angle / 180) * (max_v - min_v)) + min_v\n    pin.write_analog(angle)\n\ndef led_on(pin, brightness):\n    if not 0 <= brightness <= 1023:\n        raise ValueError('Brightness should be in range [0, 1023]')\n    pin.write_analog(brightness)\n\ndef led_off(pin):\n    pin.write_analog(0)\n\ndef light_get(pin):\n    return pin.read_analog()\n\ndef sound_get(pin):\n    return pin.read_analog()\n\ndef soil_get_moisture(pin):\n    return pin.read_analog()\n\ndef infrared_get(pin):\n    return pin.read_digital()\n\ndef joystick_get_x(pin):\n    return pin.read_analog()\n\ndef joystick_get_y(pin):\n    return pin.read_analog()\n\ndef joystick_get_button(pin):\n    cur_val = pin.read_analog()\n    return 1 if cur_val > 1000 else 0\n\ndef potentiometer_get(pin):\n    return pin.read_analog()\n\ndef get_distance(pin):\n    pin.write_digital(0)\n    pin.write_digital(1)\n    pin.write_digital(0)\n    while 0 == pin.read_digital():\n        pass\n    start_time = ticks_us()\n    while 1 == pin.read_digital():\n        pass\n    end_time = ticks_us()\n    distance = round((end_time - start_time) * 0.017, 1)\n    return distance\n\n\0"
};
